package com.scientificin.entities;

public enum Instituicao {
	UNIVERSIDADE_DE_BRASÍLIA("Universidade de Brasília","UnB"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DE_GOIÁS("Pontifícia Universidade Católica de Goiás","PUC-GO"),
	UNIVERSIDADE_CATÓLICA_DOM_BOSCO("Universidade Católica Dom Bosco","UCDB"),
	UNIVERSIDADE_DE_CUIABÁ("Universidade de Cuiabá","UNIC"),
	UNIVERSIDADE_DE_RIO_VERDE("Universidade de Rio Verde","FESURV"),
	UNIVERSIDADE_DO_ESTADO_DE_MATO_GROSSO("Universidade do Estado de Mato Grosso","UNEMAT"),
	UNIVERSIDADE_ESTADUAL_DE_GOIÁS("Universidade Estadual de Goiás","UEG"),
	UNIVERSIDADE_ESTADUAL_DE_MATO_GROSSO_DO_SUL("Universidade Estadual de Mato Grosso do Sul","UEMS"),
	UNIVERSIDADE_FEDERAL_DA_GRANDE_DOURADOS("Universidade Federal da Grande Dourados","UFGD"),
	CENTRO_UNIVERSITÁRIO_DA_GRANDE_DOURADOS("Centro Universitário da Grande Dourados","UNIGRAN"),
	CENTRO_UNIVERSITÁRIO_DE_CAMPO_GRANDE("Centro Universitário de Campo Grande","UNAES"),
	FACULDADES_INTEGRADAS_DE_TRÊS_LAGOAS("Faculdades Integradas de Três Lagoas","AEMS"),
	UNIVERSIDADE_FEDERAL_DE_GOIÁS("Universidade Federal de Goiás","UFG"),
	UNIVERSIDADE_FEDERAL_DE_MATO_GROSSO("Universidade Federal de Mato Grosso","UFMT"),
	UNIVERSIDADE_FEDERAL_DE_MATO_GROSSO_DO_SUL("Universidade Federal de Mato Grosso do Sul","UFMS"),
	UNIVERSIDADE_PARA_O_DESENVOLVIMENTO_DO_ESTADO_E_DA_REGIÃO_DO_PANTANAL("Universidade para o Desenvolvimento do Estado e da Região do Pantanal","UNIDERP"),
	UNIVERSIDADE_CATÓLICA_DE_PERNAMBUCO("Universidade Católica de Pernambuco","UNICAP"),
	UNIVERSIDADE_CATÓLICA_DO_SALVADOR("Universidade Católica do Salvador","UCSAL"),
	UNIVERSIDADE_DE_FORTALEZA("Universidade de Fortaleza","UNIFOR"),
	UNIVERSIDADE_DE_PERNAMBUCO("Universidade de Pernambuco","UPE"),
	UNIVERSIDADE_DO_ESTADO_DA_BAHIA("Universidade do Estado da Bahia","UNEB"),
	UNIVERSIDADE_DO_ESTADO_DO_RIO_GRANDE_DO_NORTE("Universidade do Estado do Rio Grande do Norte","UERN"),
	UNIVERSIDADE_ESTADUAL_DA_PARAÍBA("Universidade Estadual da Paraíba","UEPB"),
	UNIVERSIDADE_ESTADUAL_DE_ALAGOAS("Universidade Estadual de Alagoas","UNEAL"),
	UNIVERSIDADE_ESTADUAL_DE_CIÊNCIAS_DA_SAÚDE_DE_ALAGOAS("Universidade Estadual de Ciências da Saúde de Alagoas","UNCISAL"),
	UNIVERSIDADE_ESTADUAL_DE_FEIRA_DE_SANTANA("Universidade Estadual de Feira de Santana","UEFS"),
	UNIVERSIDADE_ESTADUAL_DE_SANTA_CRUZ("Universidade Estadual de Santa Cruz","UESC"),
	UNIVERSIDADE_ESTADUAL_DO_CEARÁ("Universidade Estadual do Ceará","UECE"),
	UNIVERSIDADE_ESTADUAL_DO_MARANHÃO("Universidade Estadual do Maranhão","UEMA"),
	UNIVERSIDADE_ESTADUAL_DO_PIAUÍ("Universidade Estadual do Piauí","UESPI"),
	UNIVERSIDADE_ESTADUAL_DO_SUDOESTE_DA_BAHIA("Universidade Estadual do Sudoeste da Bahia","UESB"),
	UNIVERSIDADE_ESTADUAL_VALE_DO_ACARAÚ("Universidade Estadual Vale do Acaraú","UVA"),
	UNIVERSIDADE_FEDERAL_DA_BAHIA("Universidade Federal da Bahia","UFBA"),
	UNIVERSIDADE_FEDERAL_DA_INTEGRACAO_INTERNACIONAL_DA_LUSOFONIA_AFRO_BRASILEIRA("Universidade Federal da Integração Internacional da Lusofonia Afro-Brasileira","UNILAB"),
	UNIVERSIDADE_FEDERAL_DA_PARAÍBA("Universidade Federal da Paraíba","UFPB"),
	UNIVERSIDADE_FEDERAL_DE_ALAGOAS("Universidade Federal de Alagoas","UFAL"),
	UNIVERSIDADE_FEDERAL_DE_CAMPINA_GRANDE("Universidade Federal de Campina Grande","UFCG"),
	UNIVERSIDADE_FEDERAL_DE_PERNAMBUCO("Universidade Federal de Pernambuco","UFPE"),
	UNIVERSIDADE_FEDERAL_DE_SERGIPE("Universidade Federal de Sergipe","UFS"),
	UNIVERSIDADE_FEDERAL_DO_CEARÁ("Universidade Federal do Ceará","UFC"),
	UNIVERSIDADE_FEDERAL_DO_MARANHÃO("Universidade Federal do Maranhão","UFMA"),
	UNIVERSIDADE_FEDERAL_DO_PIAUÍ("Universidade Federal do Piauí","UFPI"),
	UNIVERSIDADE_FEDERAL_DO_RECÔNCAVO_BAIANO("Universidade Federal do Recôncavo Baiano","UFRB"),
	UNIVERSIDADE_FEDERAL_DO_RIO_GRANDE_DO_NORTE("Universidade Federal do Rio Grande do Norte","UFRN"),
	UNIVERSIDADE_FEDERAL_DO_SUL_DA_BAHIA("Universidade Federal do Sul da Bahia","UFSB"),
	UNIVERSIDADE_FEDERAL_DO_OESTE_DA_BAHIA("Universidade Federal do Oeste da Bahia","UFOB"),
	UNIVERSIDADE_FEDERAL_DO_VALE_DO_SÃO_FRANCISCO("Universidade Federal do Vale do São Francisco","UNIVASF"),
	UNIVERSIDADE_FEDERAL_RURAL_DE_PERNAMBUCO("Universidade Federal Rural de Pernambuco","UFRPE"),
	UNIVERSIDADE_FEDERAL_RURAL_DO_SEMI_ÁRIDO("Universidade Federal Rural do Semi-Árido","UFERSA"),
	UNIVERSIDADE_POTIGUAR("Universidade Potiguar","UNP"),
	UNIVERSIDADE_REGIONAL_DO_CARIRI("Universidade Regional do Cariri","URCA"),
	UNIVERSIDADE_SALVADOR("Universidade Salvador","UNIFACS"),
	UNIVERSIDADE_TIRADENTES("Universidade Tiradentes","UNIT"),
	UNIVERSIDADE_DA_AMAZÔNIA("Universidade da Amazônia","UNAMA"),
	UNIVERSIDADE_DO_ESTADO_DO_AMAPÁ("Universidade do Estado do Amapá","UEAP"),
	UNIVERSIDADE_DO_ESTADO_DO_AMAZONAS("Universidade do Estado do Amazonas","UEA"),
	UNIVERSIDADE_DO_ESTADO_DO_PARÁ("Universidade do Estado do Pará","UEPA"),
	UNIVERSIDADE_DO_TOCANTINS("Universidade do Tocantins","UNITINS"),
	UNIVERSIDADE_ESTADUAL_DE_RORAIMA("Universidade Estadual de Roraima","UERR"),
	UNIVERSIDADE_ESTADUAL_DO_SABER_TRADICIONAL_DA_AMAZÔNIA("Universidade Estadual do Saber Tradicional da Amazônia","UESTA"),
	UNIVERSIDADE_FEDERAL_DE_RONDÔNIA("Universidade Federal de Rondônia","UNIR"),
	UNIVERSIDADE_FEDERAL_DE_RORAIMA("Universidade Federal de Roraima","UFRR"),
	UNIVERSIDADE_FEDERAL_DO_ACRE("Universidade Federal do Acre","UFAC"),
	UNIVERSIDADE_FEDERAL_DO_AMAPÁ("Universidade Federal do Amapá","UNIFAP"),
	UNIVERSIDADE_FEDERAL_DO_AMAZONAS("Universidade Federal do Amazonas","UFAM"),
	UNIVERSIDADE_FEDERAL_DO_OESTE_DO_PARÁ("Universidade Federal do Oeste do Pará","UFOPA"),
	UNIVERSIDADE_FEDERAL_DO_PARÁ("Universidade Federal do Pará","UFPA"),
	UNIVERSIDADE_FEDERAL_DO_TOCANTINS("Universidade Federal do Tocantins","UFT"),
	UNIVERSIDADE_FEDERAL_RURAL_DA_AMAZÔNIA("Universidade Federal Rural da Amazônia","UFRA"),
	UNIVERSIDADE_FEDERAL_DO_SUL_E_SUDESTE_DO_PARÁ("Universidade Federal do Sul e Sudeste do Pará","UNIFESSPA"),
	UNIVERSIDADE_LUTERANA_DO_BRASIL("Universidade Luterana do Brasil","ULBRA"),
	UNIVERSIDADE_DO_NORTE("Universidade do Norte","UNINORTE"),
	UNIVERSIDADE_NILTON_LINS("Universidade Nilton Lins","UNI_NILTON_LINS"),
	FACULDADE_METROPOLITANA_DE_MANAUS("Faculdade Metropolitana de Manaus","FAMETRO"),
	ESCOLA_SUPERIOR_BATISTA_DO_AMAZONAS("Escola Superior Batista do Amazonas","ESBAM"),
	CENTRO_UNIVERSITÁRIO_ESTADUAL_DA_ZONA_OESTE("Centro Universitário Estadual da Zona Oeste","UEZO"),
	CENTRO_UNIVERSITÁRIO_EURÍPIDES_DE_MARÍLIA("Centro Universitário Eurípides de Marília","UNIVEM"),
	CENTRO_UNIVERSITÁRIO_DE_LINS("Centro Universitário de Lins","UNILINS"),
	CENTRO_UNIVERSITÁRIO_DE_BELO_HORIZONTE("Centro Universitário de Belo Horizonte","UniBH"),
	CENTRO_UNIVERSITÁRIO_DE_LAVRAS("Centro Universitário de Lavras","UNILAVRAS"),
	CENTRO_UNIVERSITÁRIO_METODISTA_IZABELA_HENDRIX("Centro Universitário Metodista Izabela Hendrix","CEUNIH"),
	FACULDADE_DE_EDUCAÇÃO_TECNOLÓGICA_DO_ESTADO_DO_RIO_DE_JANEIRO("Faculdade de Educação Tecnológica do Estado do Rio de Janeiro","FAETERJ"),
	FACULDADE_DE_TECNOLOGIA_DO_ESTADO_DE_SÃO_PAULO("Faculdade de Tecnologia do Estado de São Paulo","FATEC"),
	INSTITUTO_SUPERIOR_DE_EDUCAÇÃO_DO_RIO_DE_JANEIRO("Instituto Superior de Educação do Rio de Janeiro","ISERJ"),
	INSTITUTO_SUPERIOR_DE_EDUCAÇÃO_PROFESSOR_ALDO_MUYLAERT("Instituto Superior de Educação Professor Aldo Muylaert","ISEPAM"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DE_CAMPINAS("Pontifícia Universidade Católica de Campinas","PUC-Campinas"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DE_MINAS_GERAIS("Pontifícia Universidade Católica de Minas Gerais","PUC-Minas"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DE_SÃO_PAULO("Pontifícia Universidade Católica de São Paulo","PUC-SP"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DO_RIO_DE_JANEIRO("Pontifícia Universidade Católica do Rio de Janeiro","PUC-Rio"),
	UNIVERSIDADE_ANHEMBI_MORUMBI("Universidade Anhembi Morumbi","UAM"),
	UNIVERSIDADE_BANDEIRANTE_DE_SÃO_PAULO("Universidade Bandeirante de São Paulo","UNIBAN"),
	UNIVERSIDADE_BRAZ_CUBAS("Universidade Braz Cubas","UBC"),
	UNIVERSIDADE_CAMILO_CASTELO_BRANCO("Universidade Camilo Castelo Branco","UNICASTELO"),
	UNIVERSIDADE_CÂNDIDO_MENDES("Universidade Cândido Mendes","UCAM"),
	UNIVERSIDADE_CASTELO_BRANCO("Universidade Castelo Branco","UCB"),
	UNIVERSIDADE_CATÓLICA_DE_PETRÓPOLIS("Universidade Católica de Petrópolis","UCP"),
	UNIVERSIDADE_CATÓLICA_DE_SANTOS("Universidade Católica de Santos","UNISANTOS"),
	UNIVERSIDADE_CENTRAL_PAULISTA("Universidade Central Paulista","UNICEP"),
	UNIVERSIDADE_CIDADE_DE_SÃO_PAULO("Universidade Cidade de São Paulo","UNICID"),
	UNIVERSIDADE_CRUZEIRO_DO_SUL("Universidade Cruzeiro do Sul","UNICSUL"),
	UNIVERSIDADE_DE_FRANCA("Universidade de Franca","UNIFRAN"),
	UNIVERSIDADE_DE_ITAÚNA("Universidade de Itaúna","UI"),
	UNIVERSIDADE_DE_MARÍLIA("Universidade de Marília","UNIMAR"),
	UNIVERSIDADE_DE_MOGI_DAS_CRUZES("Universidade de Mogi das Cruzes","UMC"),
	UNIVERSIDADE_DE_RIBEIRÃO_PRETO("Universidade de Ribeirão Preto","UNAERP"),
	UNIVERSIDADE_DE_SANTO_AMARO("Universidade de Santo Amaro","UNISA"),
	UNIVERSIDADE_DE_SÃO_PAULO("Universidade de São Paulo","USP"),
	UNIVERSIDADE_DE_SOROCABA("Universidade de Sorocaba","UNISO"),
	UNIVERSIDADE_DE_TAUBATÉ("Universidade de Taubaté","UNITAU"),
	UNIVERSIDADE_DE_UBERABA("Universidade de Uberaba","UNIUBE"),
	UNIVERSIDADE_DO_ESTADO_DE_MINAS_GERAIS("Universidade do Estado de Minas Gerais","UEMG"),
	UNIVERSIDADE_DO_ESTADO_DO_RIO_DE_JANEIRO("Universidade do Estado do Rio de Janeiro","UERJ"),
	UNIVERSIDADE_DO_GRANDE_ABC("Universidade do Grande ABC","UNIABC"),
	UNIVERSIDADE_DO_GRANDE_RIO_PROFESSOR_JOSÉ_DE_SOUZA_HERDY("Universidade do Grande Rio Professor José de Souza Herdy","UNIGRANRIO"),
	UNIVERSIDADE_DO_OESTE_PAULISTA("Universidade do Oeste Paulista","UNOESTE"),
	UNIVERSIDADE_DO_SAGRADO_CORAÇÃO("Universidade do Sagrado Coração","USC"),
	UNIVERSIDADE_DO_VALE_DO_PARAÍBA("Universidade do Vale do Paraíba","UNIVAP"),
	UNIVERSIDADE_DO_VALE_DO_SAPUCAÍ("Universidade do Vale do Sapucaí","UNIVÁS"),
	UNIVERSIDADE_ESTÁCIO_DE_SÁ("Universidade Estácio de Sá","UNESA"),
	UNIVERSIDADE_ESTADUAL_DE_CAMPINAS("Universidade Estadual de Campinas","UNICAMP"),
	UNIVERSIDADE_ESTADUAL_DE_MONTES_CLAROS("Universidade Estadual de Montes Claros","UNIMONTES"),
	UNIVERSIDADE_ESTADUAL_DO_NORTE_FLUMINENSE_DARCY_RIBEIRO("Universidade Estadual do Norte Fluminense Darcy Ribeiro","UENF"),
	UNIVERSIDADE_ESTADUAL_PAULISTA_JÚLIO_DE_MESQUITA_FILHO("Universidade Estadual Paulista Júlio de Mesquita Filho","UNESP"),
	UNIVERSIDADE_FEDERAL_DE_ALFENAS("Universidade Federal de Alfenas","UNIFAL"),
	UNIVERSIDADE_FEDERAL_DE_ITAJUBÁ("Universidade Federal de Itajubá","UNIFEI"),
	UNIVERSIDADE_FEDERAL_DE_JUIZ_DE_FORA("Universidade Federal de Juiz de Fora","UFJF"),
	UNIVERSIDADE_FEDERAL_DE_LAVRAS("Universidade Federal de Lavras","UFLA"),
	UNIVERSIDADE_FEDERAL_DE_MINAS_GERAIS("Universidade Federal de Minas Gerais","UFMG"),
	UNIVERSIDADE_FEDERAL_DE_OURO_PRETO("Universidade Federal de Ouro Preto","UFOP"),
	UNIVERSIDADE_FEDERAL_DE_SÃO_CARLOS("Universidade Federal de São Carlos","UFSCar"),
	UNIVERSIDADE_FEDERAL_DE_SÃO_JOÃO_DEL_REI("Universidade Federal de São João del-Rei","UFSJ"),
	UNIVERSIDADE_FEDERAL_DE_SÃO_PAULO("Universidade Federal de São Paulo","UNIFESP"),
	UNIVERSIDADE_FEDERAL_DE_UBERLÂNDIA("Universidade Federal de Uberlândia","UFU"),
	UNIVERSIDADE_FEDERAL_DE_VIÇOSA("Universidade Federal de Viçosa","UFV"),
	UNIVERSIDADE_FEDERAL_DO_ABC("Universidade Federal do ABC","UFABC"),
	UNIVERSIDADE_FEDERAL_DO_ESPÍRITO_SANTO("Universidade Federal do Espírito Santo","UFES"),
	UNIVERSIDADE_FEDERAL_DO_ESTADO_DO_RIO_DE_JANEIRO("Universidade Federal do Estado do Rio de Janeiro","UNIRIO"),
	UNIVERSIDADE_FEDERAL_DO_RIO_DE_JANEIRO("Universidade Federal do Rio de Janeiro","UFRJ"),
	UNIVERSIDADE_FEDERAL_DO_TRIÂNGULO_MINEIRO("Universidade Federal do Triângulo Mineiro","UFTM"),
	UNIVERSIDADE_FEDERAL_DOS_VALES_DO_JEQUITINHONHA_E_MUCURI("Universidade Federal dos Vales do Jequitinhonha e Mucuri","UFVJM"),
	UNIVERSIDADE_FEDERAL_FLUMINENSE("Universidade Federal Fluminense","UFF"),
	UNIVERSIDADE_FEDERAL_RURAL_DO_RIO_DE_JANEIRO("Universidade Federal Rural do Rio de Janeiro","UFRRJ"),
	UNIVERSIDADE_FUMEC("Universidade FUMEC","FUMEC"),
	UNIVERSIDADE_GAMA_FILHO("Universidade Gama Filho","UGF"),
	UNIVERSIDADE_GUARULHOS("Universidade Guarulhos","UNG"),
	UNIVERSIDADE_IBIRAPUERA("Universidade Ibirapuera","UNIB"),
	UNIVERSIDADE_IGUAÇU("Universidade Iguaçu","UNIG"),
	UNIVERSIDADE_JOSÉ_DO_ROSÁRIO_VELLANO("Universidade José do Rosário Vellano","UNIFENAS"),
	UNIVERSIDADE_METODISTA_DE_PIRACICABA("Universidade Metodista de Piracicaba","UNIMEP"),
	UNIVERSIDADE_METODISTA_DE_SÃO_PAULO("Universidade Metodista de São Paulo","UMESP"),
	UNIVERSIDADE_METROPOLITANA_DE_SANTOS("Universidade Metropolitana de Santos","UNIMES"),
	UNIVERSIDADE_MUNICIPAL_DE_SÃO_CAETANO_DO_SUL("Universidade Municipal de São Caetano do Sul","USCS"),
	UNIVERSIDADE_NOVE_DE_JULHO("Universidade Nove de Julho","UNINOVE"),
	UNIVERSIDADE_PAULISTA("Universidade Paulista","UNIP"),
	UNIVERSIDADE_PRESBITERIANA_MACKENZIE("Universidade Presbiteriana Mackenzie","MACKENZIE"),
	UNIVERSIDADE_PRESIDENTE_ANTÔNIO_CARLOS("Universidade Presidente Antônio Carlos","UNIPAC"),
	UNIVERSIDADE_SALGADO_DE_OLIVEIRA("Universidade Salgado de Oliveira","UNIVERSO"),
	UNIVERSIDADE_SANTA_CECÍLIA("Universidade Santa Cecília","UNISANTA"),
	UNIVERSIDADE_SANTA_ÚRSULA("Universidade Santa Úrsula","USU"),
	UNIVERSIDADE_SÃO_FRANCISCO("Universidade São Francisco","USF"),
	UNIVERSIDADE_SÃO_JUDAS_TADEU("Universidade São Judas Tadeu","USJT"),
	UNIVERSIDADE_SÃO_MARCOS("Universidade São Marcos","USM"),
	UNIVERSIDADE_SEVERINO_SOMBRA("Universidade Severino Sombra","USS"),
	UNIVERSIDADE_VALE_DO_RIO_DOCE("Universidade Vale do Rio Doce","UNIVALE"),
	UNIVERSIDADE_VALE_DO_RIO_VERDE("Universidade Vale do Rio Verde","UNINCOR"),
	UNIVERSIDADE_VEIGA_DE_ALMEIDA("Universidade Veiga de Almeida","UVA"),
	UNIVERSIDADE_VILA_VELHA("Universidade Vila Velha","UVV"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DO_PARANÁ("Pontifícia Universidade Católica do Paraná","PUC-PR"),
	CENTRO_UNIVERSITÁRIO_DINÂMICA_DAS_CATARATAS("Centro Universitário Dinâmica das Cataratas","UDC"),
	PONTIFÍCIA_UNIVERSIDADE_CATÓLICA_DO_RIO_GRANDE_DO_SUL("Pontifícia Universidade Católica do Rio Grande do Sul","PUC-RS"),
	UNIVERSIDADE_CATÓLICA_DE_PELOTAS("Universidade Católica de Pelotas","UCPEL"),
	UNIVERSIDADE_COMUNITÁRIA_REGIONAL_DE_CHAPECÓ("Universidade Comunitária Regional de Chapecó","UNOCHAPECÓ"),
	UNIVERSIDADE_DA_REGIÃO_DA_CAMPANHA("Universidade da Região da Campanha","URCAMP"),
	UNIVERSIDADE_DA_REGIÃO_DE_JOINVILLE("Universidade da Região de Joinville","UNIVILLE"),
	UNIVERSIDADE_BARRIGA_VERDE("Universidade Barriga Verde","UNIBAVE"),
	UNIVERSIDADE_DE_CAXIAS_DO_SUL("Universidade de Caxias do Sul","UCS"),
	UNIVERSIDADE_DE_CRUZ_ALTA("Universidade de Cruz Alta","UNICRUZ"),
	UNIVERSIDADE_DE_PASSO_FUNDO("Universidade de Passo Fundo","UPF"),
	UNIVERSIDADE_DE_SANTA_CRUZ_DO_SUL("Universidade de Santa Cruz do Sul","UNISC"),
	UNIVESIDADE_DO_ALTO_VALE_DO_RIO_DO_PIXE("Univesidade do Alto Vale do Rio do Pixe","UNIARP"),
	UNIVERSIDADE_DO_CONTESTADO("Universidade do Contestado","UNC"),
	UNIVERSIDADE_DO_ESTADO_DE_SANTA_CATARINA("Universidade do Estado de Santa Catarina","UDESC"),
	UNIVERSIDADE_DO_EXTREMO_SUL_CATARINENSE("Universidade do Extremo Sul Catarinense","UNESC"),
	UNIVERSIDADE_DO_OESTE_DE_SANTA_CATARINA("Universidade do Oeste de Santa Catarina","UNOESC"),
	UNIVERSIDADE_DO_PLANALTO_CATARINENSE("Universidade do Planalto Catarinense","UNIPLAC"),
	UNIVERSIDADE_DO_SUL_DE_SANTA_CATARINA("Universidade do Sul de Santa Catarina","UNISUL"),
	UNIVERSIDADE_DO_VALE_DO_RIO_DOS_SINOS("Universidade do Vale do Rio dos Sinos","UNISINOS"),
	UNIVERSIDADE_DO_VALE_DO_ITAJAÍ("Universidade do Vale do Itajaí","UNIVALI"),
	UNIVERSIDADE_ESTADUAL_DE_LONDRINA("Universidade Estadual de Londrina","UEL"),
	UNIVERSIDADE_ESTADUAL_DE_MARINGÁ("Universidade Estadual de Maringá","UEM"),
	UNIVERSIDADE_ESTADUAL_DO_PARANÁ("Universidade Estadual do Paraná","UNESPAR"),
	UNIVERSIDADE_ESTADUAL_DE_PONTA_GROSSA("Universidade Estadual de Ponta Grossa","UEPG"),
	UNIVERSIDADE_ESTADUAL_DO_CENTRO_OESTE("Universidade Estadual do Centro-Oeste","UNICENTRO"),
	UNIVERSIDADE_ESTADUAL_DO_NORTE_DO_PARANÁ("Universidade Estadual do Norte do Paraná","UENP"),
	UNIVERSIDADE_ESTADUAL_DO_OESTE_DO_PARANÁ("Universidade Estadual do Oeste do Paraná","UNIOESTE"),
	UNIVERSIDADE_ESTADUAL_DO_RIO_GRANDE_DO_SUL("Universidade Estadual do Rio Grande do Sul","UERGS"),
	UNIVERSIDADE_FEDERAL_DA_FRONTEIRA_DO_SUL("Universidade Federal da Fronteira do Sul","UFFS"),
	UNIVERSIDADE_FEDERAL_DA_INTEGRAÇÃO_LATINO_AMERICANA("Universidade Federal da Integração Latino-Americana","UNILA"),
	UNIVERSIDADE_FEDERAL_DE_CIÊNCIAS_DA_SAÚDE_DE_PORTO_ALEGRE("Universidade Federal de Ciências da Saúde de Porto Alegre","UFCSPA"),
	UNIVERSIDADE_FEDERAL_DE_PELOTAS("Universidade Federal de Pelotas","UFPEL"),
	UNIVERSIDADE_FEDERAL_DE_SANTA_CATARINA("Universidade Federal de Santa Catarina","UFSC"),
	UNIVERSIDADE_FEDERAL_DE_SANTA_MARIA("Universidade Federal de Santa Maria","UFSM"),
	UNIVERSIDADE_FEDERAL_DO_PAMPA("Universidade Federal do Pampa","UNIPAMPA"),
	UNIVERSIDADE_FEDERAL_DO_PARANÁ("Universidade Federal do Paraná","UFPR"),
	UNIVERSIDADE_FEDERAL_DO_RIO_GRANDE("Universidade Federal do Rio Grande","FURG"),
	UNIVERSIDADE_FEDERAL_DO_RIO_GRANDE_DO_SUL("Universidade Federal do Rio Grande do Sul","UFRGS"),
	UNIVERSIDADE_FEEVALE("Universidade Feevale","FEEVALE"),
	UNIVERSIDADE_NORTE_DO_PARANÁ("Universidade Norte do Paraná","UNOPAR"),
	UNIVERSIDADE_PARA_O_DESENVOLVIMENTO_DO_ALTO_VALE_DO_ITAJAÍ("Universidade para o Desenvolvimento do Alto Vale do Itajaí","UNIDAVI"),
	UNIVERSIDADE_PARANAENSE("Universidade Paranaense","UNIPAR"),
	UNIVERSIDADE_POSITIVO("Universidade Positivo","UP"),
	UNIVERSIDADE_REGIONAL_DE_BLUMENAU("Universidade Regional de Blumenau","FURB"),
	UNIVERSIDADE_REGIONAL_DO_NOROESTE_DO_ESTADO_DO_RIO_GRANDE_DO_SUL("Universidade Regional do Noroeste do Estado do Rio Grande do Sul","UNIJUI"),
	UNIVERSIDADE_REGIONAL_INTEGRADA_DO_ALTO_URUGUAI_E_DAS_MISSÕES("Universidade Regional Integrada do Alto Uruguai e das Missões","URI"),
	UNIVERSIDADE_TECNOLÓGICA_FEDERAL_DO_PARANÁ("Universidade Tecnológica Federal do Paraná","UTFPR"),
	UNIVERSIDADE_TUIUTI_DO_PARANÁ("Universidade Tuiuti do Paraná","UTP");
	
	private String name;
	private String sigla;
	
	private Instituicao (String name, String sigla) {
		this.name=name;
		this.sigla=sigla;
	}
	
	public String getSigla() {
		return sigla;
	}
	
	public String getName() {
		return name;
	}

}
